### ISSUE TITLE
LimeSDR Mini Support

### ISSUE THREAD

**Issue by mattcoates** [osqzss/LimeGPS#2]
Hi,

Does this support the Lime SDR Mini? When I run LimeGPS I get the following error:

```
matt@matt-lenovo:~/LimeGPS$ ./LimeGPS -e brdc0350.18n
Opening and initializing device...
Reference clock 40.00 MHz
SetPllFrequency: timeout, busy bit is still 1
ERROR: Failed to set sample rate: 
Closing device...
matt@matt-lenovo:~/LimeGPS$ 
```

Thanks,

Matt

**Comment by osqzss** [comment]
I don't have a Mini and have never tested my code with it.
The following thread of a LimeSDR forum could be helpful:
https://discourse.myriadrf.org/t/problems-with-limesdr-mini/2394/26

**Comment by tasanakorn** [comment]
change  (limegps.c, Line 442)

`int setSampleRate = LMS_SetSampleRate(device, (double)TX_SAMPLERATE, 0);`

to

`int setSampleRate = LMS_SetSampleRate(device, (double)TX_SAMPLERATE, 1);`

**Comment by chrismyers2000** [comment]
Thanks @tasanakorn , 
Confirmed working on my LimeSDR Mini.
